### ISSUE TITLE
[ Bug report ] Jumping anchor

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#1740] opened 2022-10-28 00:40 UTC
## Required

**What is the issue?**

When I visit 

https://docs.temporal.io/application-development/foundations#connect-to-a-cluster

the correct heading flashes, but then I see a lower down section of the page.

**What is the expected behavior?**

It stays on the anchor heading

## Additional context (optional—the more we know, the faster it goes)

**Screenshots:**

https://user-images.githubusercontent.com/251288/198422871-d3344656-fa3e-46a9-b4bf-5be4c96ca234.mov

**Browser and version:**

Latest Mac Chrome

**Comment by djmagee** [comment] 2022-10-28 02:33
Confirmed on Firefox 106.0.2 and Edge 106.0.1370.52, both on Windows 10.0.19045.2130.

**Comment by feedmeapples** [comment] 2022-11-03 16:41
same for https://docs.temporal.io/references/web-ui-environment-variables#temporal_notify_on_new_version

**Comment by vkarpov15** [comment] 2023-01-15 19:18
It looks like this is due to link previews. The link previews show up for an instance before disappearing, and that's causing the layout shift. For example, you can see that https://docs.temporal.io/temporal#temporal-platform shows up correctly, but with https://docs.temporal.io/temporal#temporal-application the header shifts up a bit out of view. I haven't been able to figure out why this is happening or how to fix yet, but I'm working on it.

**Comment by axfelix** [comment] 2023-10-12 17:02
This was fixed without being closed (see above links); closing.

**Closed by axfelix** 2023-10-12 17:02 UTC
