### ISSUE TITLE
[Feature Request] Add Node Build page

### ISSUE THREAD

**Issue by lorensr** [temporalio/documentation#689] opened 2021-10-15 17:44 UTC
### Describe the solution you'd like

- Explanation of our recommended tsconfig/ts-node/nodemon config, used in [hello-world](https://github.com/temporalio/samples-node/tree/main/hello-world)
- Explanation of ESM alternative: [fetch-esm](https://github.com/temporalio/samples-node/tree/main/fetch-esm)
- Recommend using `--enable-source-maps` for those running `node` on a `lib/dist` dir

**Comment by bergundy** [comment] 2021-10-15 17:52
Yes, please.
I'd also add the rust toolkit explanation here.
This is mostly a duplicate of https://github.com/temporalio/documentation/issues/679.
Let's make sure one of these has all of the information and close the other.

**Closed** 2021-10-15 21:28 UTC
Labels: enhancement
